# Generated by Django 3.2 on 2025-12-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
